# Generated by Django 4.2.4 on 2024-02-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_remove_agent_first_name_remove_agent_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_organizer",
            field=models.BooleanField(default=True),
        ),
    ]
